#if defined(CAPS_WORD_ENABLE)
#    define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#endif // CAPS_WORD_ENABLE

#define ENABLE_COMPILE_KEYCODE

#ifdef LEADER_ENABLE
#    define LEADER_PER_KEY_TIMING
#    define LEADER_TIMEOUT 275
#    define LEADER_NO_TIMEOUT
#endif // LEADER_ENABLE

#ifdef RGB_MATRIX_ENABLE
#    define CAPS_LOCK_INDICATOR_COLOR RGB_PURPLE
#    define CAPS_LOCK_INDICATOR_UNDERGLOW
#    define CAPS_LOCK_INDICATOR_LIGHT_ALPHAS
#    define FN_LAYER_INDICATOR_1_COLOR RGB_CYAN
#    define FN_LAYER_INDICATOR_2_COLOR RGB_MAGENTA
#    define FN_LAYER_INDICATOR_UNDERGLOW
#    define LEADER_INDICATOR_COLOR RGB_PINK
#    define FN_LAYER_TRANSPARENT_KEYS_OFF
// #    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
// #    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_PINWHEEL
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON
// #    define RGB_MATRIX_DEFAULT_SPD 15 // Speed
// #    define RGB_MATRIX_DEFAULT_SPD 7 // Speed
#    define RGB_MATRIX_DEFAULT_SPD 0 // Speed
// #    define RGB_MATRIX_TIMEOUT 900000 // 15 minutes
// #    define RGB_MATRIX_TIMEOUT 600000 // 10 minutes
#    define RGB_MATRIX_TIMEOUT 300000 // 5 minutes
// #    define RGB_MATRIX_TIMEOUT 180000 // 3 minutes
#    ifdef RGB_MATRIX_CAPS_LOCK_INDEX
#        undef RGB_MATRIX_CAPS_LOCK_INDEX
#    endif
#    define RGB_MATRIX_CAPS_LOCK_INDEX 76
#endif // RGB_MATRIX_ENABLE
